-- Migration 009 : Performance tuning
-- Audit ARCH_BACKEND_2026-04-19 : DB-2 (auth_rls_initplan) + DB-6 (unindexed FK) + DB-7 (unused indexes)
-- Generated by API+Hooks Unification Architect subagent.

BEGIN;

-- ---------------------------------------------------------------
-- Section A: DB-2 Fix auth_rls_initplan (55 policies)
-- Wrap auth.uid() in (select ...) so Postgres computes initPlan once
-- per query instead of per row.
-- ---------------------------------------------------------------

DROP POLICY IF EXISTS "Users manage own achievements" ON public.achievements;
CREATE POLICY "Users manage own achievements" ON public.achievements
  FOR ALL
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users manage own availability" ON public.availability;
CREATE POLICY "Users manage own availability" ON public.availability
  FOR ALL
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users manage own challenges" ON public.challenges;
CREATE POLICY "Users manage own challenges" ON public.challenges
  FOR ALL
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users see own challenges" ON public.challenges;
CREATE POLICY "Users see own challenges" ON public.challenges
  FOR SELECT
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users manage own checkins" ON public.checkins;
CREATE POLICY "Users manage own checkins" ON public.checkins
  FOR ALL
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users see own checkins" ON public.checkins;
CREATE POLICY "Users see own checkins" ON public.checkins
  FOR SELECT
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Conversation participants" ON public.conversations;
CREATE POLICY "Conversation participants" ON public.conversations
  FOR SELECT
  TO public
  USING ((((select auth.uid()) = user_a) OR ((select auth.uid()) = user_b)));

DROP POLICY IF EXISTS "Users create conversations" ON public.conversations;
CREATE POLICY "Users create conversations" ON public.conversations
  FOR INSERT
  TO public
  WITH CHECK ((((select auth.uid()) = user_a) OR ((select auth.uid()) = user_b)));

DROP POLICY IF EXISTS "Users manage own feed activities" ON public.feed_activities;
CREATE POLICY "Users manage own feed activities" ON public.feed_activities
  FOR ALL
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users see own feedback" ON public.feedback;
CREATE POLICY "Users see own feedback" ON public.feedback
  FOR SELECT
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users submit feedback" ON public.feedback;
CREATE POLICY "Users submit feedback" ON public.feedback
  FOR INSERT
  TO public
  WITH CHECK (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Auth users self-join flash plans" ON public.flash_plan_participants;
CREATE POLICY "Auth users self-join flash plans" ON public.flash_plan_participants
  FOR INSERT
  TO public
  WITH CHECK (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users delete own participation" ON public.flash_plan_participants;
CREATE POLICY "Users delete own participation" ON public.flash_plan_participants
  FOR DELETE
  TO public
  USING ((((select auth.uid()) = user_id) OR ((select auth.uid()) IN ( SELECT flash_plans.creator_id FROM flash_plans WHERE (flash_plans.id = flash_plan_participants.flash_plan_id)))));

DROP POLICY IF EXISTS "Users update own participation" ON public.flash_plan_participants;
CREATE POLICY "Users update own participation" ON public.flash_plan_participants
  FOR UPDATE
  TO public
  USING ((((select auth.uid()) = user_id) OR ((select auth.uid()) IN ( SELECT flash_plans.creator_id FROM flash_plans WHERE (flash_plans.id = flash_plan_participants.flash_plan_id)))));

DROP POLICY IF EXISTS "Auth users create flash plans" ON public.flash_plans;
CREATE POLICY "Auth users create flash plans" ON public.flash_plans
  FOR INSERT
  TO public
  WITH CHECK (((select auth.uid()) = creator_id));

DROP POLICY IF EXISTS "Creators delete own flash plans" ON public.flash_plans;
CREATE POLICY "Creators delete own flash plans" ON public.flash_plans
  FOR DELETE
  TO public
  USING (((select auth.uid()) = creator_id));

DROP POLICY IF EXISTS "Creators update own flash plans" ON public.flash_plans;
CREATE POLICY "Creators update own flash plans" ON public.flash_plans
  FOR UPDATE
  TO public
  USING (((select auth.uid()) = creator_id));

DROP POLICY IF EXISTS "Users manage own interactions" ON public.interactions;
CREATE POLICY "Users manage own interactions" ON public.interactions
  FOR INSERT
  TO public
  WITH CHECK (((select auth.uid()) = from_user));

DROP POLICY IF EXISTS "Users see interactions to them" ON public.interactions;
CREATE POLICY "Users see interactions to them" ON public.interactions
  FOR SELECT
  TO public
  USING ((((select auth.uid()) = to_user) OR ((select auth.uid()) = from_user)));

DROP POLICY IF EXISTS "Users manage own karma" ON public.karma_transactions;
CREATE POLICY "Users manage own karma" ON public.karma_transactions
  FOR ALL
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users see own karma" ON public.karma_transactions;
CREATE POLICY "Users see own karma" ON public.karma_transactions
  FOR SELECT
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Message participants" ON public.messages;
CREATE POLICY "Message participants" ON public.messages
  FOR SELECT
  TO public
  USING ((EXISTS ( SELECT 1 FROM conversations c WHERE ((c.id = messages.conversation_id) AND (((select auth.uid()) = c.user_a) OR ((select auth.uid()) = c.user_b))))));

DROP POLICY IF EXISTS "Users send messages" ON public.messages;
CREATE POLICY "Users send messages" ON public.messages
  FOR INSERT
  TO public
  WITH CHECK ((((select auth.uid()) = sender_id) AND (EXISTS ( SELECT 1 FROM conversations c WHERE ((c.id = messages.conversation_id) AND (((select auth.uid()) = c.user_a) OR ((select auth.uid()) = c.user_b)))))));

DROP POLICY IF EXISTS "Users delete own modes" ON public.mode_activations;
CREATE POLICY "Users delete own modes" ON public.mode_activations
  FOR DELETE
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users manage own modes" ON public.mode_activations;
CREATE POLICY "Users manage own modes" ON public.mode_activations
  FOR INSERT
  TO public
  WITH CHECK (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users update own modes" ON public.mode_activations;
CREATE POLICY "Users update own modes" ON public.mode_activations
  FOR UPDATE
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Participants can delete plans" ON public.plans;
CREATE POLICY "Participants can delete plans" ON public.plans
  FOR DELETE
  TO public
  USING ((((select auth.uid()) = user_a) OR ((select auth.uid()) = user_b)));

DROP POLICY IF EXISTS "Participants can insert plans" ON public.plans;
CREATE POLICY "Participants can insert plans" ON public.plans
  FOR INSERT
  TO public
  WITH CHECK ((((select auth.uid()) = user_a) OR ((select auth.uid()) = user_b)));

DROP POLICY IF EXISTS "Participants can read plans" ON public.plans;
CREATE POLICY "Participants can read plans" ON public.plans
  FOR SELECT
  TO public
  USING ((((select auth.uid()) = user_a) OR ((select auth.uid()) = user_b)));

DROP POLICY IF EXISTS "Participants can update plans" ON public.plans;
CREATE POLICY "Participants can update plans" ON public.plans
  FOR UPDATE
  TO public
  USING ((((select auth.uid()) = user_a) OR ((select auth.uid()) = user_b)));

DROP POLICY IF EXISTS "Users delete own prompts" ON public.profile_prompts;
CREATE POLICY "Users delete own prompts" ON public.profile_prompts
  FOR DELETE
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users manage own prompts" ON public.profile_prompts;
CREATE POLICY "Users manage own prompts" ON public.profile_prompts
  FOR INSERT
  TO public
  WITH CHECK (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users update own prompts" ON public.profile_prompts;
CREATE POLICY "Users update own prompts" ON public.profile_prompts
  FOR UPDATE
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users delete own profile" ON public.profiles;
CREATE POLICY "Users delete own profile" ON public.profiles
  FOR DELETE
  TO authenticated
  USING (((select auth.uid()) = id));

DROP POLICY IF EXISTS "Users insert own profile" ON public.profiles;
CREATE POLICY "Users insert own profile" ON public.profiles
  FOR INSERT
  TO public
  WITH CHECK (((select auth.uid()) = id));

DROP POLICY IF EXISTS "Users update own profile" ON public.profiles;
CREATE POLICY "Users update own profile" ON public.profiles
  FOR UPDATE
  TO public
  USING (((select auth.uid()) = id));

DROP POLICY IF EXISTS "purchases_select_own" ON public.purchases;
CREATE POLICY "purchases_select_own" ON public.purchases
  FOR SELECT
  TO authenticated
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "purchases_update_own" ON public.purchases;
CREATE POLICY "purchases_update_own" ON public.purchases
  FOR UPDATE
  TO authenticated
  USING (((select auth.uid()) = user_id))
  WITH CHECK (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users report" ON public.reports;
CREATE POLICY "Users report" ON public.reports
  FOR INSERT
  TO public
  WITH CHECK (((select auth.uid()) = reporter_id));

DROP POLICY IF EXISTS "Users see own reports" ON public.reports;
CREATE POLICY "Users see own reports" ON public.reports
  FOR SELECT
  TO public
  USING (((select auth.uid()) = reporter_id));

DROP POLICY IF EXISTS "Users write reviews" ON public.reviews;
CREATE POLICY "Users write reviews" ON public.reviews
  FOR INSERT
  TO public
  WITH CHECK (((select auth.uid()) = reviewer_id));

DROP POLICY IF EXISTS "Auth users can create rooms as host" ON public.rooms;
CREATE POLICY "Auth users can create rooms as host" ON public.rooms
  FOR INSERT
  TO public
  WITH CHECK (((select auth.uid()) = host_id));

DROP POLICY IF EXISTS "Hosts can delete own rooms" ON public.rooms;
CREATE POLICY "Hosts can delete own rooms" ON public.rooms
  FOR DELETE
  TO public
  USING (((select auth.uid()) = host_id));

DROP POLICY IF EXISTS "Hosts can update own rooms" ON public.rooms;
CREATE POLICY "Hosts can update own rooms" ON public.rooms
  FOR UPDATE
  TO public
  USING (((select auth.uid()) = host_id));

DROP POLICY IF EXISTS "Inviters manage their invites" ON public.squad_invites;
CREATE POLICY "Inviters manage their invites" ON public.squad_invites
  FOR ALL
  TO public
  USING (((select auth.uid()) = inviter_id));

DROP POLICY IF EXISTS "Squad creators can manage their squads" ON public.squads;
CREATE POLICY "Squad creators can manage their squads" ON public.squads
  FOR ALL
  TO public
  USING (((select auth.uid()) = creator_id));

DROP POLICY IF EXISTS "Squad members can view squads" ON public.squads;
CREATE POLICY "Squad members can view squads" ON public.squads
  FOR SELECT
  TO public
  USING ((((select auth.uid()) = ANY (members)) OR ((select auth.uid()) = creator_id)));

DROP POLICY IF EXISTS "Users manage own streak" ON public.streaks;
CREATE POLICY "Users manage own streak" ON public.streaks
  FOR ALL
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "subscriptions_select_own" ON public.subscriptions;
CREATE POLICY "subscriptions_select_own" ON public.subscriptions
  FOR SELECT
  TO authenticated
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "subscriptions_update_own" ON public.subscriptions;
CREATE POLICY "subscriptions_update_own" ON public.subscriptions
  FOR UPDATE
  TO authenticated
  USING (((select auth.uid()) = user_id))
  WITH CHECK (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users manage own tonight" ON public.tonight_preferences;
CREATE POLICY "Users manage own tonight" ON public.tonight_preferences
  FOR ALL
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users manage own contacts" ON public.trusted_contacts;
CREATE POLICY "Users manage own contacts" ON public.trusted_contacts
  FOR ALL
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users see own contacts" ON public.trusted_contacts;
CREATE POLICY "Users see own contacts" ON public.trusted_contacts
  FOR SELECT
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users manage own settings" ON public.user_settings;
CREATE POLICY "Users manage own settings" ON public.user_settings
  FOR ALL
  TO public
  USING (((select auth.uid()) = user_id));

DROP POLICY IF EXISTS "Users see own settings" ON public.user_settings;
CREATE POLICY "Users see own settings" ON public.user_settings
  FOR SELECT
  TO public
  USING (((select auth.uid()) = user_id));

-- ---------------------------------------------------------------
-- Section B: DB-6 Add indexes on 12 unindexed FK
-- ---------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_checkins_conversation_id_fk ON public.checkins (conversation_id);
CREATE INDEX IF NOT EXISTS idx_conversations_user_b_fk ON public.conversations (user_b);
CREATE INDEX IF NOT EXISTS idx_feedback_user_id_fk ON public.feedback (user_id);
CREATE INDEX IF NOT EXISTS idx_messages_sender_id_fk ON public.messages (sender_id);
CREATE INDEX IF NOT EXISTS idx_plans_proposed_by_fk ON public.plans (proposed_by);
CREATE INDEX IF NOT EXISTS idx_reports_reported_id_fk ON public.reports (reported_id);
CREATE INDEX IF NOT EXISTS idx_reports_reporter_id_fk ON public.reports (reporter_id);
CREATE INDEX IF NOT EXISTS idx_reviews_conversation_id_fk ON public.reviews (conversation_id);
CREATE INDEX IF NOT EXISTS idx_reviews_reviewed_id_fk ON public.reviews (reviewed_id);
CREATE INDEX IF NOT EXISTS idx_squad_invites_inviter_id_fk ON public.squad_invites (inviter_id);
CREATE INDEX IF NOT EXISTS idx_squad_invites_used_by_fk ON public.squad_invites (used_by);
CREATE INDEX IF NOT EXISTS idx_swipe_undos_target_id_fk ON public.swipe_undos (target_id);

-- ---------------------------------------------------------------
-- Section C: DB-7 Drop 44 unused indexes flagged by advisor
-- ---------------------------------------------------------------

DROP INDEX IF EXISTS public.idx_squads_creator;
DROP INDEX IF EXISTS public.idx_squads_created_at;
DROP INDEX IF EXISTS public.idx_squad_invites_squad;
DROP INDEX IF EXISTS public.idx_squad_invites_code;
DROP INDEX IF EXISTS public.idx_squad_invites_created_at;
DROP INDEX IF EXISTS public.idx_feed_activities_user;
DROP INDEX IF EXISTS public.idx_feed_activities_type;
DROP INDEX IF EXISTS public.idx_plans_user_a;
DROP INDEX IF EXISTS public.idx_plans_user_b;
DROP INDEX IF EXISTS public.idx_plans_when;
DROP INDEX IF EXISTS public.idx_flash_plans_creator;
DROP INDEX IF EXISTS public.idx_flash_plans_status_when;
DROP INDEX IF EXISTS public.idx_flash_plans_deadline;
DROP INDEX IF EXISTS public.idx_challenges_user;
DROP INDEX IF EXISTS public.idx_challenges_created;
DROP INDEX IF EXISTS public.idx_mode_active;
DROP INDEX IF EXISTS public.idx_profiles_online;
DROP INDEX IF EXISTS public.idx_messages_conversation;
DROP INDEX IF EXISTS public.idx_karma_transactions_created_at;
DROP INDEX IF EXISTS public.idx_streaks_user;
DROP INDEX IF EXISTS public.idx_fpp_plan;
DROP INDEX IF EXISTS public.idx_fpp_user;
DROP INDEX IF EXISTS public.idx_rooms_host;
DROP INDEX IF EXISTS public.idx_checkins_user;
DROP INDEX IF EXISTS public.idx_checkins_status;
DROP INDEX IF EXISTS public.idx_checkins_created_at;
DROP INDEX IF EXISTS public.idx_rooms_status_started;
DROP INDEX IF EXISTS public.idx_user_settings_user;
DROP INDEX IF EXISTS public.idx_rooms_mode;
DROP INDEX IF EXISTS public.idx_availability_user;
DROP INDEX IF EXISTS public.idx_availability_day;
DROP INDEX IF EXISTS public.idx_subscriptions_stripe_sub_id;
DROP INDEX IF EXISTS public.idx_subscriptions_status;
DROP INDEX IF EXISTS public.idx_subscriptions_customer_id;
DROP INDEX IF EXISTS public.idx_swipe_undos_user_id;
DROP INDEX IF EXISTS public.idx_swipe_undos_user_date;
DROP INDEX IF EXISTS public.idx_purchases_user_id;
DROP INDEX IF EXISTS public.idx_purchases_payment_intent;
DROP INDEX IF EXISTS public.idx_purchases_status;
DROP INDEX IF EXISTS public.idx_purchases_product_type;
DROP INDEX IF EXISTS public.idx_user_wallet_user_id;
DROP INDEX IF EXISTS public.idx_match_caps_user_id;
DROP INDEX IF EXISTS public.flash_plans_type_idx;
DROP INDEX IF EXISTS public.flash_plans_when_at_idx;

-- ---------------------------------------------------------------
-- Section D: Recreate FK-covering indexes that were also in the
-- "unused" list but were the ONLY index covering their foreign key.
-- Dropping them silently re-introduced unindexed_foreign_keys lints.
-- These are named with _fk suffix to signal purpose; they will be
-- re-flagged as unused until traffic exercises them, but the
-- FK-without-index ERROR-level lint is resolved.
-- ---------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_challenges_user_id_fk ON public.challenges (user_id);
CREATE INDEX IF NOT EXISTS idx_checkins_user_id_fk ON public.checkins (user_id);
CREATE INDEX IF NOT EXISTS idx_feed_activities_user_id_fk ON public.feed_activities (user_id);
CREATE INDEX IF NOT EXISTS idx_flash_plan_participants_user_id_fk ON public.flash_plan_participants (user_id);
CREATE INDEX IF NOT EXISTS idx_flash_plans_creator_id_fk ON public.flash_plans (creator_id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id_fk ON public.messages (conversation_id);
CREATE INDEX IF NOT EXISTS idx_plans_user_b_fk ON public.plans (user_b);
CREATE INDEX IF NOT EXISTS idx_purchases_user_id_fk ON public.purchases (user_id);
CREATE INDEX IF NOT EXISTS idx_rooms_host_id_fk ON public.rooms (host_id);
CREATE INDEX IF NOT EXISTS idx_squad_invites_squad_id_fk ON public.squad_invites (squad_id);
CREATE INDEX IF NOT EXISTS idx_squads_creator_id_fk ON public.squads (creator_id);
CREATE INDEX IF NOT EXISTS idx_swipe_undos_user_id_fk ON public.swipe_undos (user_id);

COMMIT;
